# Leistungsnachweis

Es muss eine voll funktionsfähige Web App erstellt werden (Resultat Übung 10), in einer eigenen Gruppe veröffentlicht werden und als Link per E-Mail an Pascal Ochsner versendet werden.
Gehe folgendermassen vor: Erstelle in ArcGIS Online eine neue eigene Gruppe. Benenne die Gruppe als «Leistungsnachweis Vorname Name». Definiere folgende Gruppeneigenschaften:

- Wer kann diese Gruppe sehen? -> Nur Gruppenmitglieder
- Wer kann Mitglied dieser Gruppe sein? -> Nur Mitglieder der eigenen Organisation
- Wie können Personen dieser Gruppe beitreten? -> Nach Einladung
- Wer kann Inhalte beitragen? -> Alle Gruppenmitglieder

Füge Pascal Ochsner (ocpa_zhaw) Deiner eigenen Gruppe «Leistungsnachweis Vorname Name» als Mitglied hinzu (via Benutzer einladen) ohne eine Bestätigung anzufordern.
Veröffentliche die Web Map inklusive Web App aus Übung 10 für alle Mitglieder Deiner Gruppe «Leistungsnachweis Vorname Name».

Sende bis spätestens Sonntagabend **18. Dezember 2022** eine E-Mail mit folgendem Inhalt an ***pascal.ochsner@zhaw.ch***: 

:::{.callout}
Betreff:
Modul AGI: Leistungsnachweis Web GIS 

Text:
Hallo Pascal

Den Nachweis für meinen Leistungsnachweis – meine persönliche Web App – kannst Du via folgendem Link aufrufen Link: https://zhaw.maps.arcgis.com/..... 

Beste Grüsse,
Vorname Name
:::
